-- V14: Seed Golf Saudi IT Processes
-- Description: Add sample IT processes for Golf Saudi based on their IT department operations

-- Insert Golf Saudi IT Processes into Technology Division (ID=3)
-- Process Owner: John Doe (ID=1) - IT Manager

INSERT INTO processes (
    process_name,
    process_code,
    description,
    organizational_unit_id,
    process_owner,
    status,
    is_critical,
    created_at,
    created_by,
    updated_at,
    updated_by,
    version,
    is_deleted
) VALUES
(
    'IT Project Management',
    'PROC-001',
    'The IT Project Management Process encompasses a structured approach designed to ensure the effective and efficient execution of IT projects from initiation to closure. This process aligns with organizational goals and leverages best practices to manage scope, resources, time, and budget effectively.',
    3,
    'John Doe',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'IT Asset Management - Creation',
    'PROC-002',
    'The IT Asset Management - Creation process is designed to systematically track and manage Golf Saudi''s IT assets throughout their lifecycle. This process ensures that IT assets are acquired, deployed and maintained effectively, supporting both operational efficiency and strategic decision-making.',
    3,
    'John Doe',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'IT Asset Management - Retrieval',
    'PROC-003',
    'The IT Asset Management - Retrieval process is designed to manage the efficient retrieval of Golf Saudi IT assets from end-users, whether due to asset retirement, reallocation, or replacement. This process ensures that assets are tracked, recovered, and either reused or disposed of in a secure and compliant manner.',
    3,
    'Jane Smith',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'IT Assets Management Maintenance/Repairs',
    'PROC-004',
    'The IT Asset Management - Maintenance/Repairs process is facilitating proactive and reactive maintenance measures, enhancing system reliability and minimizing downtime due to equipment failures.',
    3,
    'Jane Smith',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Service Desk Management',
    'PROC-005',
    'The Service Desk Management process acts as the primary contact point for end-users facing issues or requiring support with IT services. This process is designed to facilitate the resolution of incidents and requests, manage communications during service disruptions, and ensure user satisfaction.',
    3,
    'Bob Johnson',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Incident Management',
    'PROC-006',
    'The Incident Management process is a core function of Golf Saudi IT department aimed at restoring normal service operation as quickly as possible while minimizing the adverse impact on business operations. This process ensures that every incident is logged, managed, and resolved in a manner that meets agreed-upon service levels and maintains high levels of business continuity and user satisfaction.',
    3,
    'Bob Johnson',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Problem Management',
    'PROC-007',
    'The Problem Management Process aimed at minimizing the impact of repeatable incidents by addressing the root causes of those incidents. Unlike Incident Management, which focuses on resolving the symptoms and restoring service quickly, Problem Management Process seeks to eliminate recurring incidents and prevent future ones by identifying, documenting, and resolving the underlying problems.',
    3,
    'Alice Williams',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'IT Configuration Management',
    'PROC-008',
    'The IT Configuration Management process involves maintaining information about configuration items required to deliver an IT service. This process ensures that there are accurate records of all CIs and that changes to these CIs are controlled and documented for managing changes, resolving incidents, and ensuring compliance.',
    3,
    'Alice Williams',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Define Service Level Agreements',
    'PROC-009',
    'The Define Service Level Agreements process involves the negotiation, establishment, monitoring, reporting, and review of SLAs to ensure that the specified standards of service are achieved.',
    3,
    'Charlie Brown',
    'ACTIVE',
    FALSE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Manage IT Vendors/Suppliers',
    'PROC-010',
    'This process ensures that vendor performance aligns with the strategic goals and operational requirements of Golf Saudi IT department. Effective management of IT vendors and suppliers helps ensure service quality, and mitigate risks associated with vendor performance.',
    3,
    'Charlie Brown',
    'ACTIVE',
    FALSE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Access Management',
    'PROC-011',
    'This process of granting authorized users the right to use a service while preventing access to non-authorized users and ensures that the right individuals have the appropriate access at the right times, enhancing both security and productivity.',
    3,
    'John Doe',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Application Security Compliance',
    'PROC-012',
    'The Application Security Compliance process ensures that all Golf Saudi applications meet defined security standards and regulatory requirements. This process designed to protect sensitive data, maintaining privacy, and preventing unauthorized access or breaches. It encompasses the implementation of security measures throughout the application lifecycle.',
    3,
    'John Doe',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Network Management',
    'PROC-013',
    'Network Management process is focusing on the maintenance, operation, and monitoring of an Golf Saudi networking infrastructure. This process ensures that the network remains efficient, reliable, and secure, supporting both everyday operations and strategic business initiatives.',
    3,
    'Jane Smith',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Change Management',
    'PROC-014',
    'The primary goal for this process is to implement changes in a controlled manner, minimizing any potential impact on services and ensuring that changes deliver their intended benefits.',
    3,
    'Jane Smith',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Backup',
    'PROC-015',
    'This process is fundamental to data protection strategy, ensuring data integrity, availability, and continuity in the event of hardware failure, data corruption, or a security breach such as ransomware.',
    3,
    'Bob Johnson',
    'ACTIVE',
    TRUE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
),
(
    'Archiving',
    'PROC-016',
    'The Archiving Process is a structured approach to managing the retention, storage, and eventual disposal of records and data that are no longer actively needed but must be kept for legal, regulatory, or historical reasons.',
    3,
    'Bob Johnson',
    'ACTIVE',
    FALSE,
    CURRENT_TIMESTAMP,
    'System',
    CURRENT_TIMESTAMP,
    'System',
    0,
    FALSE
);

