-- =====================================================
-- BCM Platform - Database Migration V1 (H2 Compatible)
-- Create Organizational Units Table (Self-Referencing Hierarchy)
-- =====================================================

-- Create organizational_units table
CREATE TABLE organizational_units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Basic Information
    unit_code VARCHAR(50) UNIQUE,
    unit_name VARCHAR(255) NOT NULL,
    description TEXT,
    
    -- Self-Referencing Hierarchy
    parent_unit_id BIGINT,
    
    -- Unit Classification
    unit_type VARCHAR(50) NOT NULL,
    is_bia_eligible BOOLEAN NOT NULL DEFAULT false,
    
    -- Unit Leadership
    unit_head VARCHAR(255),
    unit_head_email VARCHAR(255),
    unit_head_phone VARCHAR(50),
    
    -- Location Reference (will be created in later migration)
    location_id BIGINT,
    
    -- Criticality Information
    criticality_tier VARCHAR(20),
    criticality_score INTEGER,
    
    -- Organizational Metrics
    employee_count INTEGER,
    annual_budget DECIMAL(15, 2),
    
    -- Flexible Metadata
    metadata TEXT,
    
    -- Audit Fields
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    version BIGINT DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    
    -- Foreign Key Constraints
    CONSTRAINT fk_parent_unit FOREIGN KEY (parent_unit_id) 
        REFERENCES organizational_units(id) ON DELETE SET NULL
);

-- Create indexes for performance
CREATE INDEX idx_parent_unit ON organizational_units(parent_unit_id);
CREATE INDEX idx_unit_type ON organizational_units(unit_type);
CREATE INDEX idx_bia_eligible ON organizational_units(is_bia_eligible);
CREATE INDEX idx_unit_code ON organizational_units(unit_code);
CREATE INDEX idx_is_deleted ON organizational_units(is_deleted);

-- =====================================================
-- Sample Data - Organizational Hierarchy
-- =====================================================

-- Level 0: Organization (Root)
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, employee_count, annual_budget, created_by) 
VALUES ('ACME', 'ACME Corporation', 'Global technology and services company', NULL, 'ORGANIZATION', false, 5000, 500000000.00, 'system');

-- Level 1: Divisions
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, employee_count, annual_budget, created_by)
VALUES
('OPS', 'Operations Division', 'Manages all operational activities', 1, 'DIVISION', false, 1500, 150000000.00, 'system'),
('TECH', 'Technology Division', 'IT and technology services', 1, 'DIVISION', false, 2000, 200000000.00, 'system'),
('FIN', 'Finance Division', 'Financial operations and planning', 1, 'DIVISION', false, 500, 50000000.00, 'system'),
('HR', 'Human Resources Division', 'People and culture', 1, 'DIVISION', false, 300, 30000000.00, 'system'),
('SALES', 'Sales & Marketing Division', 'Revenue generation', 1, 'DIVISION', true, 700, 70000000.00, 'system');

-- Level 2: Departments under Operations
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by) 
VALUES 
('OPS-CS', 'Customer Service', 'Customer support and service', 2, 'DEPARTMENT', true, 'Sarah Johnson', 'sarah.johnson@acme.com', 200, 20000000.00, 'system'),
('OPS-LOG', 'Logistics', 'Supply chain and logistics', 2, 'DEPARTMENT', true, 'Mike Chen', 'mike.chen@acme.com', 300, 30000000.00, 'system'),
('OPS-QA', 'Quality Assurance', 'Quality control and assurance', 2, 'DEPARTMENT', true, 'Emily Davis', 'emily.davis@acme.com', 150, 15000000.00, 'system');

-- Level 2: Departments under Technology
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('TECH-INFRA', 'IT Infrastructure', 'Infrastructure and operations', 3, 'DEPARTMENT', true, 'David Kim', 'david.kim@acme.com', 250, 25000000.00, 'system'),
('TECH-DEV', 'Software Development', 'Application development', 3, 'DEPARTMENT', false, 'Lisa Wang', 'lisa.wang@acme.com', 500, 50000000.00, 'system'),
('TECH-SEC', 'Cybersecurity', 'Information security', 3, 'DEPARTMENT', false, 'James Brown', 'james.brown@acme.com', 100, 10000000.00, 'system'),
('TECH-DATA', 'Data & Analytics', 'Data management and analytics', 3, 'DEPARTMENT', true, 'Maria Garcia', 'maria.garcia@acme.com', 150, 15000000.00, 'system');

-- Level 3: Teams under Software Development (parent_unit_id = 11, which is Software Development)
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('TECH-DEV-FE', 'Frontend Team', 'Web and mobile UI development', 11, 'TEAM', true, 'Alex Martinez', 'alex.martinez@acme.com', 150, 15000000.00, 'system'),
('TECH-DEV-BE', 'Backend Team', 'Server-side development', 11, 'TEAM', true, 'Rachel Lee', 'rachel.lee@acme.com', 200, 20000000.00, 'system'),
('TECH-DEV-MOB', 'Mobile Team', 'iOS and Android development', 11, 'TEAM', true, 'Tom Wilson', 'tom.wilson@acme.com', 150, 15000000.00, 'system');

-- Level 3: Teams under Cybersecurity (parent_unit_id = 12, which is Cybersecurity)
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('TECH-SEC-SOC', 'Security Operations Team', 'Security monitoring and incident response', 12, 'TEAM', true, 'Marcus Johnson', 'marcus.johnson@acme.com', 40, 4000000.00, 'system'),
('TECH-SEC-IAM', 'Identity & Access Management Team', 'User access and authentication', 12, 'TEAM', true, 'Sophia Williams', 'sophia.williams@acme.com', 30, 3000000.00, 'system'),
('TECH-SEC-GRC', 'Governance, Risk & Compliance Team', 'Security policies and compliance', 12, 'TEAM', true, 'Nathan Brown', 'nathan.brown@acme.com', 30, 3000000.00, 'system');

-- Level 2: Departments under Finance
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('FIN-ACC', 'Accounting', 'Financial accounting and reporting', 4, 'DEPARTMENT', false, 'Jennifer Taylor', 'jennifer.taylor@acme.com', 150, 15000000.00, 'system'),
('FIN-PAY', 'Payroll', 'Employee compensation', 4, 'DEPARTMENT', false, 'Robert Anderson', 'robert.anderson@acme.com', 50, 5000000.00, 'system'),
('FIN-FPA', 'FP&A', 'Financial planning and analysis', 4, 'DEPARTMENT', true, 'Susan White', 'susan.white@acme.com', 100, 10000000.00, 'system');

-- Level 3: Teams under Accounting (parent_unit_id = 20, which is Accounting after Cybersecurity teams)
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('FIN-ACC-AR', 'Accounts Receivable Team', 'Customer billing and collections', 20, 'TEAM', true, 'Patricia Moore', 'patricia.moore@acme.com', 50, 5000000.00, 'system'),
('FIN-ACC-AP', 'Accounts Payable Team', 'Vendor payments and reconciliation', 20, 'TEAM', true, 'Daniel Jackson', 'daniel.jackson@acme.com', 50, 5000000.00, 'system'),
('FIN-ACC-GL', 'General Ledger Team', 'Financial reporting and compliance', 20, 'TEAM', true, 'Laura Thompson', 'laura.thompson@acme.com', 50, 5000000.00, 'system');

-- Level 3: Teams under Payroll (parent_unit_id = 21, which is Payroll after Cybersecurity teams)
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by)
VALUES
('FIN-PAY-DOM', 'Domestic Payroll Team', 'US employee payroll processing', 21, 'TEAM', true, 'Christopher Martin', 'christopher.martin@acme.com', 25, 2500000.00, 'system'),
('FIN-PAY-INT', 'International Payroll Team', 'Global employee payroll processing', 21, 'TEAM', true, 'Amanda Rodriguez', 'amanda.rodriguez@acme.com', 25, 2500000.00, 'system');

-- Level 2: Departments under HR
INSERT INTO organizational_units (unit_code, unit_name, description, parent_unit_id, unit_type, is_bia_eligible, unit_head, unit_head_email, employee_count, annual_budget, created_by) 
VALUES 
('HR-REC', 'Recruitment', 'Talent acquisition', 5, 'DEPARTMENT', true, 'Michelle Harris', 'michelle.harris@acme.com', 100, 10000000.00, 'system'),
('HR-L&D', 'Learning & Development', 'Employee training and development', 5, 'DEPARTMENT', true, 'Kevin Clark', 'kevin.clark@acme.com', 80, 8000000.00, 'system');

-- =====================================================
-- Summary Statistics
-- =====================================================
-- Total Units: 29
-- Organizations: 1
-- Divisions: 5 (1 is BIA-eligible: Sales & Marketing)
-- Departments: 12 (5 are BIA-eligible: Customer Service, Logistics, QA, IT Infrastructure, Data & Analytics, FP&A)
-- Teams: 11 (all are BIA-eligible)
--
-- Hierarchical Structure:
-- - ACME Corporation (Organization)
--   - Operations Division
--     - Customer Service (DEPT) ✓ BIA-eligible
--     - Logistics (DEPT) ✓ BIA-eligible
--     - Quality Assurance (DEPT) ✓ BIA-eligible
--   - Technology Division
--     - IT Infrastructure (DEPT) ✓ BIA-eligible
--     - Software Development (DEPT) - has 3 teams
--       - Frontend Team ✓ BIA-eligible
--       - Backend Team ✓ BIA-eligible
--       - Mobile Team ✓ BIA-eligible
--     - Cybersecurity (DEPT) - has 3 teams
--       - Security Operations Team ✓ BIA-eligible
--       - Identity & Access Management Team ✓ BIA-eligible
--       - Governance, Risk & Compliance Team ✓ BIA-eligible
--     - Data & Analytics (DEPT) ✓ BIA-eligible
--   - Finance Division
--     - Accounting (DEPT) - has 3 teams
--       - Accounts Receivable Team ✓ BIA-eligible
--       - Accounts Payable Team ✓ BIA-eligible
--       - General Ledger Team ✓ BIA-eligible
--     - Payroll (DEPT) - has 2 teams
--       - Domestic Payroll Team ✓ BIA-eligible
--       - International Payroll Team ✓ BIA-eligible
--     - FP&A (DEPT) ✓ BIA-eligible
--   - Human Resources Division
--     - Recruitment (DEPT) ✓ BIA-eligible
--     - Learning & Development (DEPT) ✓ BIA-eligible
--   - Sales & Marketing Division ✓ BIA-eligible
--
-- Total BIA-Eligible Units (Leaf Nodes): 17
-- (5 departments + 11 teams + 1 division)

